### ISSUE TITLE
vite4+vue3+js 构建错误

### ISSUE THREAD

**Issue by ZXHHYJ** [WarrenJones/vite-plugin-require-transform#46]
日志：
"C:\Program Files\nodejs\npm.cmd" run build

> mytube-vue@0.0.0 build
> vite build

vite v4.3.5 building for production...
✓ 12862 modules transformed.
✓ built in 27.39s
[commonjs--resolver] Identifier '_vite_plugin_require_transform_index' has already been declared (11:6) in C:/Users/95744/WebstormProjects/mytube-vue/node_modules/date-fns/format/index.js
file: C:/Users/95744/WebstormProjects/mytube-vue/node_modules/date-fns/format/index.js:11:6
 9: var _index2 = _interopRequireDefault(require("../subMilliseconds/index.js"));
10: var _index3 = _interopRequireDefault(require("../toDate/index.js"));
11: var _index4 = _interopRequireDefault(require("../_lib/format/formatters/index.js"));
          ^
12: var _index5 = _interopRequireDefault(require("../_lib/format/longFormatters/index.js"));
13: var _index6 = _interopRequireDefault(require("../_lib/getTimezoneOffsetInMilliseconds/index.js"));
error during build:
SyntaxError: Identifier '_vite_plugin_require_transform_index' has already been declared (11:6) in C:/Users/95744/WebstormProjects/mytube-vue/node_modules/date-fns/format/index.js
    at pp$4.raise (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:21134:13)
    at pp$3.declareName (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:21210:26)
    at pp$7.checkLValSimple (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:19818:48)
    at pp$7.checkLValPattern (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:19860:10)
    at pp$8.parseVarId (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:18994:8)
    at pp$8.parseVar (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:18976:10)
    at pp$8.parseVarStatement (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:18842:8)
    at pp$8.parseStatement (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:18590:17)
    at pp$8.parseTopLevel (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:18492:21)
    at Parser.parse (file:///C:/Users/95744/WebstormProjects/mytube-vue/node_modules/rollup/dist/es/shared/node-entry.js:18264:15)

Process finished with exit code 1

vite.confit.js:
`
export default defineConfig({
    plugins: [vue(), requireTransform({
        fileRegex: /.js$|.vue$/
    })],
    resolve: {
        alias: {
            '@': fileURLToPath(new URL('./src', import.meta.url))
        }
    }
    }
})
`
要如何解决？
似乎可以尝试添加一个拦截器，让其排除部分文件夹，比如node模块里的js文件？

**Comment by WarrenJones** [comment]
seems this case can be resolved by setting fileRegex or fileHandler.Just checkout the readme file in case 1 or case 3 you can fix it
